[JENKINS-55787] Switch labels from entry to checkbox
jenkinsci/mailer-plugin pull request #52
Opened 2019-02-12 17:01 UTC by jsoref

[https://issues.jenkins-ci.org/browse/JENKINS-55787](https://issues.jenkins-ci.org/browse/JENKINS-55787)

Basically checkboxes should have labels, splitting the labels away from their checkboxes is poor UX, poor accessibility. This change brings the layout more inline with how normal settings UIs lay out checkboxes.

This supersedes #51

2019-03-29 21:20 UTC, alecharp commented
Thank you @jsoref for your contribution, again :tada: !

I've made a screenshot without you fix:

![2019-03-29-22-03-19_891x328](https://user-images.githubusercontent.com/985955/55262714-f1e97580-526e-11e9-81e4-10565c599b3a.png)

and with:

![2019-03-29-22-05-57_887x329](https://user-images.githubusercontent.com/985955/55262713-f1e97580-526e-11e9-9e2f-c15da2fec0cc.png)

to help me visualized the diff. I'm still not fluent in Jelly :wink:.

I do understand your point, having the checkbox before the label is normally what we expect. But I fear that in Jenkins, the way the configuration is visualized, it might be misunderstood. 

The overall configurations are "designed" like a `table`, with 
- a left column for the field label / title
- a right colum for the field value (with textbox, textarea, checkbox, etc.)

I fear that the modification of this "structure" might cause some incomprehension. 

I'm really sorry to engage the discusion a month and 1/2 after you opened this PR, this is a really big mistake on my side.

2019-09-03 10:17 UTC, oleg-nenashev commented
@jsoref gentle ping, are you still interested in it?

2019-09-03 16:09 UTC, jsoref commented
@alecharp: The table format for the configuration will be removed once I get enough of these changes merged. And this is one of countably few outliers.

2019-09-10 08:34 UTC, oleg-nenashev commented
No strong opinion from me. We should be indeed moving towards the table-less UI, but right now it rather downgrades the UX. What would be the impact if we merge this change after the table removal PRs are merged?

2019-09-10 17:19 UTC, jsoref commented
It looks a bit uglier in table-less. I'm happy to let some of these wait until we switch.

2020-10-24 23:52 UTC, jsoref commented
Fwiw, divs landed in https://github.com/jenkinsci/jenkins/commit/87b72f57c3eaee2814fd63c12a9bc88b46015f28

2021-03-09 14:13 UTC, oleg-nenashev reviewed
On 2.277.1 RC it makes no differene:

Before and after:
![image](https://user-images.githubusercontent.com/3000480/110483176-bfe31e00-80e9-11eb-953d-26b1b81ad9ff.png)


The indent below the control is weird, but the patch does change that

2024-04-26 20:39 UTC, jglick requested changes
`field` must remain on `f:entry` in order for help to work.

2024-04-26 20:39 UTC, jglick commented on src/main/resources/hudson/tasks/Mailer/global.jelly
> +        <f:checkbox title="${%Use SSL}" field="useSsl" />
```suggestion
      <f:entry field="useSsl">
        <f:checkbox title="${%Use SSL}"/>
```

2024-04-29 12:20 UTC, jglick commented
Is this still needed? It already looks OK to me in trunk:
![mailer](https://github.com/jenkinsci/mailer-plugin/assets/154109/aaad9e79-08ad-4567-9193-adfad725a87f)

2024-04-30 14:17 UTC, jsoref commented on src/main/resources/hudson/tasks/Mailer/global.jelly
>          <f:checkbox />
```suggestion
      <f:entry field="useTls">
        <f:checkbox title="${%Use TLS}"/>
```

2024-04-30 14:20 UTC, jsoref commented
I'm not sure if it's still needed. We turned off our jenkins instance a while ago and are now relying exclusively on GitHub for CI (we used Google Cloud build for a bit).

2024-05-22 14:11 UTC, alecharp commented
Based on Jesse comment, I'm closing this for now. 
Thank you anyway @jsoref for the time you spent on this.

2024-05-22 14:11 UTC, closed without merging